### ISSUE TITLE
Error: [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by ishitat** [HunanTV/redis-ctl#29]
Getting below error when trying to run  python main.py :

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    main()
  File "main.py", line 5, in main
    app = config.App(config)
  File "/home/user/redis-ctl/app/core.py", line 68, in __init__
    self.stats_client = self.init_stats_client(config)
  File "/home/user/redis-ctl/app/core.py", line 169, in init_stats_client
    return Client(**config.OPEN_FALCON)
  File "/home/user/redis-ctl/thirdparty/openfalcon.py", line 28, in __init__
    self.reconnect()
  File "/home/user/redis-ctl/thirdparty/openfalcon.py", line 36, in reconnect
    self.socket = socket.create_connection(self.write_addr)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -3] Temporary failure in name resolution

**Comment by zheplusplus** [comment]
> Temporary failure in name resolution

Seems like a problem with your DNS.

**Comment by ishitat** [comment]
How to resolve ? any idea ? I have changed the IP in main.py file

**Comment by zheplusplus** [comment]
What's the output of a `nslookup` or `dig` command to the domain for Open Falcon?
